import React from "react";
import Header from "../../components/Header";
import { useSignInWithGoogle } from "react-firebase-hooks/auth";
import { auth } from "../../firebase";
import { useRouter } from "next/router";
import Head from "next/head";

type SignPageProps = {};

const SignPage: React.FC<SignPageProps> = () => {
  const router = useRouter();
  const [signInWithGoogle, userCred, loading, error] =
    useSignInWithGoogle(auth);

  const createUserDocument = () => {
    signInWithGoogle();
    router.push(`/`);
  };

  return (
    <div>
      <Head>
        <title>Instagram Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://drive.google.com/uc?export=download&id=1eqWbbCrvcw6w6W-3eCEFkDu-9L2MbRaH"
        />
      </Head>
      <Header />
      <div className="flex flex-col items-center justify-center min-h-screen py-2 -m-56 px-14 text-center pt-60">
        <img
          className="w-70"
          src="https://www.pngmart.com/files/13/Instagram-Logo-PNG-Transparent.png"
          alt=""
        />
        <p className="font-xs italic">
          This is not a Real app, it is build for educational purpose only
        </p>
        <div className="mt-20">
          <div>
            <button
              className="p-3 bg-blue-500 rounded-lg text-white"
              onClick={createUserDocument}
            >
              Sign in with Google
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
export default SignPage;
