import Head from "next/head";
import React, { useEffect } from "react";
import { motion } from "framer-motion";
import { getSession } from "next-auth/react";
import { useRouter } from "next/router";

import Header from "../../components/Header";
import MainProfile from "../../components/profilePage/MainProfile";

type ProfilePageProps = {
  session: any;
};

const ProfilePage: React.FC<ProfilePageProps> = ({ session }) => {
  const router = useRouter();

  useEffect(() => {
    if (!session) {
      router.push("/");
    } else return;
  }, [session]);

  return (
    <motion.div
      initial={{ opacity: 0 }}
      whileInView={{ opacity: 1 }}
      viewport={{ once: true }}
    >
      <Head>
        <title>Instagram Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://i.postimg.cc/wjt4vkWx/pngwing-com-1.png"
        />
      </Head>
      <Header />
      <MainProfile />
    </motion.div>
  );
};
export default ProfilePage;

export async function getServerSideProps(context: any) {
  const session = await getSession(context);

  return {
    props: {
      session: session,
    },
  };
}
