import Head from "next/head";
import React from "react";
import { motion } from "framer-motion";

import Header from "../../components/Header";
import MainProfile from "../../components/profilePage/MainProfile";

type ProfilePageProps = {};

const ProfilePage: React.FC<ProfilePageProps> = () => {
  return (
    <motion.div
      initial={{ opacity: 0 }}
      whileInView={{ opacity: 1 }}
      viewport={{ once: true }}
    >
      <Head>
        <title>Instagram Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://i.postimg.cc/wjt4vkWx/pngwing-com-1.png"
        />
      </Head>
      <Header />
      <MainProfile />
    </motion.div>
  );
};
export default ProfilePage;
