import type { NextPage } from "next";
import Head from "next/head";
import Header from "../components/Header";
import Feed from "../components/Feed";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Instagram Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://i.postimg.cc/wjt4vkWx/pngwing-com-1.png"
        />
      </Head>
      <Header />
      <Feed />
    </div>
  );
};

export default Home;
